import { Inter } from "next/font/google";
import "./globals.css";
import GlobalNavBar from "./custom_components/GlobalNavBar";
import NavbarPrimary from "./custom_components/NavbarPrimary";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalNavBar />
        <NavbarPrimary />
        {children}
      </body>
    </html>
  );
}
