import { Inter } from "next/font/google";
import "./globals.css";
import GlobalNavBar from "./custom_components/GlobalNavBar";
import NavbarPrimary from "./custom_components/NavbarPrimary";

import store from "./redux/store";
import StoreProvider from "./redux/StoreProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalNavBar />
        <StoreProvider>
          <NavbarPrimary />
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 4000,
              style: {
                background: "#363636",
                color: "#fff",
              },
            }}
          />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
